version: "3"

services:
  kajian-auth:
    image: ${LOCAL_REGISTRY}/kajian-auth
    container_name: kajian_auth
    build: .
    ports:
      - "5001:80"
    networks:
      - my_network
    volumes:
      - /usr/env:/var/config
      - /usr/local/var/log:/var/log
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - env_volume:/var/config
    networks:
      database-network:
        ipv4_address: 192.168.123.101
      my_network:

  redis:
    image: redis:latest
    container_name: my_redis_container
    # ports:
    #   - "6379:6379"
    networks:
      - my_network
    volumes:
      - ./redis_data:/data

networks:
  my_network:
    driver: bridge
  database-network:
    external: true
    driver: bridge

volumes:
  db_data:
  env_volume:
    external: true
    name: env-volume
