name: ci

on:
  push:
    branches:
      - master
      - ci_cd 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract short SHA
        id: vars
        run: echo "::set-output name=short_sha::${GITHUB_SHA::7}"
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: uchupx/kajian-auth-go:${{ steps.vars.outputs.short_sha }}-dev
